/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;


import EmployeeData.Employee;
import Organization.org_class;
import Organization.org_directory_class;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
/**
 *
 * @author dsnik
 */
public class Manage_EmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Manage_EmployeeJPanel
     */
       private org_directory_class organizationDir;
    private JPanel userProcessContainer;
    private static Logger log = Logger.getLogger(Manage_EmployeeJPanel.class);
    private static final String CLASS_NAME = Manage_EmployeeJPanel.class.getName();
      
    public Manage_EmployeeJPanel(JPanel userProcessContainer, org_directory_class organizationDir) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;               
        populateOrganizationEmpComboBox();
         populateOrganizationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPaneTable_Employee = new javax.swing.JScrollPane();
        jTable_Employee = new javax.swing.JTable();
        lbl_Organization = new javax.swing.JLabel();
        jComboBox_Org = new javax.swing.JComboBox<>();
        jLabel_emp_org = new javax.swing.JLabel();
        jComboBox_emp_org = new javax.swing.JComboBox<>();
        TXT_EMP_NAME = new javax.swing.JTextField();
        LBL_EMP_NAME = new javax.swing.JLabel();
        BTN_CREATE_EMP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE EMPLOYEE");

        jTable_Employee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME"
            }
        ));
        jScrollPaneTable_Employee.setViewportView(jTable_Employee);

        lbl_Organization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Organization.setText("Organization");

        jComboBox_Org.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_Org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_OrgActionPerformed(evt);
            }
        });

        jLabel_emp_org.setText("Organization");

        jComboBox_emp_org.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LBL_EMP_NAME.setText("NAME");

        BTN_CREATE_EMP.setText("CREATE EMPLOYEE");
        BTN_CREATE_EMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CREATE_EMPActionPerformed(evt);
            }
        });

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneTable_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(jLabel_emp_org, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(LBL_EMP_NAME)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jComboBox_emp_org, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BTN_CREATE_EMP)
                                            .addComponent(TXT_EMP_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Organization, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(jComboBox_Org, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Organization, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Org, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneTable_Employee, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_emp_org, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_emp_org, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TXT_EMP_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_EMP_NAME))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_CREATE_EMP)
                    .addComponent(jButton1))
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CREATE_EMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CREATE_EMPActionPerformed
        // TODO add your handling code here:
        org_class organization = (org_class) jComboBox_emp_org.getSelectedItem();
        String name = TXT_EMP_NAME.getText().trim();
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid input");
            return;
        }
        ArrayList<String> namecheck = new ArrayList<>();
        for(Employee o:organization.getEmployeeDirectory().getEmpList())
        {
            namecheck.add(o.getEmpName().toLowerCase());
            
        }
        if(namecheck.contains(name.toLowerCase()))
        {
            JOptionPane.showMessageDialog(null,"Employee already exists");
            return;
        }
        log.debug("Enterprise admin adding following employee \t" +name+ "in following Organization \t" +organization+ "\t" +CLASS_NAME);
        organization.getEmployeeDirectory().CreateEmployeeData(name);
        populateTable(organization);
        TXT_EMP_NAME.setText("");
    }//GEN-LAST:event_BTN_CREATE_EMPActionPerformed

    private void jComboBox_OrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_OrgActionPerformed
        // TODO add your handling code here:
        org_class organization = (org_class) jComboBox_Org.getSelectedItem();
        if (organization != null){
            populateTable(organization);
    }//GEN-LAST:event_jComboBox_OrgActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed
private void populateTable(org_class organization){
        DefaultTableModel model = (DefaultTableModel) jTable_Employee.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmpList()){
            Object[] row = new Object[2];
            row[0] = employee.getEmpid();
            row[1] = employee.getEmpName();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_CREATE_EMP;
    private javax.swing.JLabel LBL_EMP_NAME;
    private javax.swing.JTextField TXT_EMP_NAME;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_Org;
    private javax.swing.JComboBox<String> jComboBox_emp_org;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_emp_org;
    private javax.swing.JScrollPane jScrollPaneTable_Employee;
    private javax.swing.JTable jTable_Employee;
    private javax.swing.JLabel lbl_Organization;
    // End of variables declaration//GEN-END:variables

    private void populateOrganizationComboBox() {
   jComboBox_Org.removeAllItems();
        
        for (org_class org : organizationDir.getOrgList()){
            jComboBox_Org.addItem(org);
        } }

    private void populateOrganizationEmpComboBox() {
     jComboBox_emp_org.removeAllItems();
        
        for (org_class organization : organizationDir.getOrgList()){
            jComboBox_emp_org.addItem(organization);
        }
    }
}
