/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;

/**
 *
 * @author dsnik
 */
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
public class Manage_UserAccountJPanel extends javax.swing.JPanel {
 private JPanel container;
    private Enterprise enterprise;
    private static Logger log = Logger.getLogger(Manage_UserAccountJPanel.class);
    private static final String CLASS_NAME = Manage_UserAccountJPanel.class.getName();
    /**
     * Creates new form Manage_UserAccountJPanel
     */
    public Manage_UserAccountJPanel(JPanel container, Enterprise enterprise) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        populateData();
        populateOrganizationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LBL_ORG = new javax.swing.JLabel();
        LBL_EMP = new javax.swing.JLabel();
        LBL_ROLE = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LBL_PASSWORD = new javax.swing.JLabel();
        TXT_USER_NAME = new javax.swing.JTextField();
        TXT_PASSWORD = new javax.swing.JTextField();
        BTN_BACK_MANG_USER_aCC = new javax.swing.JButton();
        BTN_CREATE_USER_aCC = new javax.swing.JButton();
        Jcombobox_Org = new javax.swing.JComboBox();
        JComboBox_Emp = new javax.swing.JComboBox();
        JComboBox_role = new javax.swing.JComboBox();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE USER ACCOUNT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USER NAME", "ROLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        LBL_ORG.setText("ORGANIZATION");

        LBL_EMP.setText("EMPLOYEEE");

        LBL_ROLE.setText("ROLE");

        jLabel2.setText("USER NAME");

        LBL_PASSWORD.setText("PASSWORD");

        TXT_USER_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_USER_NAMEActionPerformed(evt);
            }
        });

        TXT_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_PASSWORDActionPerformed(evt);
            }
        });

        BTN_BACK_MANG_USER_aCC.setText("BACK");
        BTN_BACK_MANG_USER_aCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACK_MANG_USER_aCCActionPerformed(evt);
            }
        });

        BTN_CREATE_USER_aCC.setText("CREATE USER ACCOUNT");
        BTN_CREATE_USER_aCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CREATE_USER_aCCActionPerformed(evt);
            }
        });

        Jcombobox_Org.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        Jcombobox_Org.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Jcombobox_Org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jcombobox_OrgActionPerformed(evt);
            }
        });

        JComboBox_Emp.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        JComboBox_Emp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        JComboBox_role.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        JComboBox_role.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(LBL_ROLE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(LBL_PASSWORD))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JComboBox_role, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LBL_EMP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(JComboBox_Emp, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_BACK_MANG_USER_aCC)
                        .addGap(154, 154, 154)
                        .addComponent(BTN_CREATE_USER_aCC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(LBL_ORG)
                        .addGap(28, 28, 28)
                        .addComponent(Jcombobox_Org, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_ORG)
                    .addComponent(Jcombobox_Org, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_EMP)
                    .addComponent(LBL_ROLE)
                    .addComponent(JComboBox_Emp, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JComboBox_role, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXT_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_PASSWORD)
                    .addComponent(TXT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_BACK_MANG_USER_aCC)
                    .addComponent(BTN_CREATE_USER_aCC))
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_USER_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_USER_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_USER_NAMEActionPerformed

    private void TXT_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_PASSWORDActionPerformed

    private void BTN_CREATE_USER_aCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CREATE_USER_aCCActionPerformed
        // TODO add your handling code here:
          String userName = TXT_USER_NAME.getText().trim();
        String password = TXT_PASSWORD.getText();
        Organization organization = (Organization) Jcombobox_Org.getSelectedItem();
        Employee employee = (Employee) JComboBox_Emp.getSelectedItem();
        Role role = (Role) JComboBox_role.getSelectedItem();
        ArrayList<String>usernamecheck = new ArrayList<>();
        for(UserAccount e: organization.getUserAccountDirectory().getUserAccountList())
        {
            usernamecheck.add(e.getUsername());
            
        }
        if(usernamecheck.contains(userName))
        {
            JOptionPane.showMessageDialog(null,"UserName already exists");
            return;
        }
        if(userName.isEmpty()||password.isEmpty())
        {
         JOptionPane.showMessageDialog(null,"Please enter a Valid input");
            return;   
        }
        log.debug("Enterprise admin creating user with name \t" +userName+ "Role" +role+ "In Organization" +organization+ "\t" +CLASS_NAME);
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        
        populateData();
        TXT_USER_NAME.setText("");
        TXT_PASSWORD.setText("");
    }//GEN-LAST:event_BTN_CREATE_USER_aCCActionPerformed

    private void BTN_BACK_MANG_USER_aCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACK_MANG_USER_aCCActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_BTN_BACK_MANG_USER_aCCActionPerformed

    private void Jcombobox_OrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jcombobox_OrgActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) Jcombobox_Org.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
        }
    }//GEN-LAST:event_Jcombobox_OrgActionPerformed

 

    private void populateOrganizationComboBox() {
      Jcombobox_Org.removeAllItems();

        for (Organization org_class : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Jcombobox_Org.addItem(org_class);
       }
    }
   
        


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACK_MANG_USER_aCC;
    private javax.swing.JButton BTN_CREATE_USER_aCC;
    private javax.swing.JComboBox JComboBox_Emp;
    private javax.swing.JComboBox JComboBox_role;
    private javax.swing.JComboBox Jcombobox_Org;
    private javax.swing.JLabel LBL_EMP;
    private javax.swing.JLabel LBL_ORG;
    private javax.swing.JLabel LBL_PASSWORD;
    private javax.swing.JLabel LBL_ROLE;
    private javax.swing.JTextField TXT_PASSWORD;
    private javax.swing.JTextField TXT_USER_NAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateEmployeeComboBox(Organization organization) {
    JComboBox_Emp.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            JComboBox_Emp.addItem(employee);
        } }

    private void populateRoleComboBox(Organization organization) {
      JComboBox_role.removeAllItems();
        for (Role role : organization.getSupportedRole()){
            JComboBox_role.addItem(role);
        }  

    } 

    private void populateData() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) jTable1.getModel()).addRow(row);
            }
        } }
}
