/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;

/**
 *
 * @author dsnik
 */
import Chemical.ChemicalClass;
import Enterprise.Chemical_Enterprise_class;
import Enterprise.Drug_Enterprise_class;
import Enterprise.Enterprise_class;
import Enterprise.Hospital_Enterprise_class;
import Enterprise.Pharmacy_Enterprise_class;
import Organization.org_class;
import Organization.org_class.Type;
import Organization.org_directory_class;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

public class Manage_OrgJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Manage_OrgJPanel
     */
    private org_directory_class organizationDir;
      private JPanel userProcessContainer;
      private Enterprise_class enterprise;
      private static Logger log = Logger.getLogger(Manage_OrgJPanel.class);
      private static final String CLASS_NAME = Manage_OrgJPanel.class.getName();
      
    public Manage_OrgJPanel(JPanel userProcessContainer,org_directory_class organizationDir,Enterprise_class enterprise) {
        initComponents();
        this.organizationDir = organizationDir;
        this.userProcessContainer = userProcessContainer;
        this.enterprise=enterprise;
        populateTable();
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane_Table_Org = new javax.swing.JScrollPane();
        jTable_Org = new javax.swing.JTable();
        lbl_Org_Type = new javax.swing.JLabel();
        jComboBox_Org_type = new javax.swing.JComboBox<>();
        Btn_back_Manage_Org = new javax.swing.JButton();
        btn_Add_org = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE ORGANIZATIONS");

        jTable_Org.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane_Table_Org.setViewportView(jTable_Org);

        lbl_Org_Type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Org_Type.setText("Organization Type");

        jComboBox_Org_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Btn_back_Manage_Org.setText("BACK");
        Btn_back_Manage_Org.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_back_Manage_OrgActionPerformed(evt);
            }
        });

        btn_Add_org.setText("ADD ORGANIZATION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lbl_Org_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jComboBox_Org_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btn_Add_org))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(Btn_back_Manage_Org))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jScrollPane_Table_Org, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(491, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Org_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Org_Type, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Add_org)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Table_Org, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Btn_back_Manage_Org)
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_back_Manage_OrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_back_Manage_OrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_back_Manage_OrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_back_Manage_Org;
    private javax.swing.JButton btn_Add_org;
    private javax.swing.JComboBox<String> jComboBox_Org_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane_Table_Org;
    private javax.swing.JTable jTable_Org;
    private javax.swing.JLabel lbl_Org_Type;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
      jComboBox_Org_type.removeAllItems();
        for (org_class.Type type : org_class.Type.values()){
            
            if (!type.getValue().equals(org_class.Type.Admin.getValue()))
            {
//                
                if(enterprise instanceof Hospital_Enterprise_class){
                    
                     jComboBox_Org_type.addItem(org_class.Type.Doctor);
                     jComboBox_Org_type.addItem(org_class.Type.Lab);
                     break;
                }else if(enterprise instanceof Pharmacy_Enterprise_class){
                    
                     jComboBox_Org_type.addItem(org_class.Type.Pharmacy);
                     break;
                    
                }
                else if(enterprise instanceof Drug_Enterprise_class)
                {
                     jComboBox_Org_type.addItem(org_class.Type.Drug);
                     break;
                }
                else if(enterprise instanceof Chemical_Enterprise_class)
                {
                  jComboBox_Org_type.addItem(org_class.Type.Chemical);
                     break;  
                }
                 
                    
            }
        }   
    
    }

    private void populateComboBox() {
       DefaultTableModel model = (DefaultTableModel) jTable_Org.getModel();
        
        model.setRowCount(0);
        
        for (org_class organization : organizationDir.getOrgList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrgID();
            row[1] = organization.getOrgName();
            
            model.addRow(row);
        }
    
    }
}
