/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.AdminRole;

/**
 *
 * @author dsnik
 */
import EmployeeData.Employee;
import Enterprise.Enterprise_class;
import Organization.org_class;
import Role.Role_class;
import User_account.User_account_class;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
public class Manage_UserAccountJPanel extends javax.swing.JPanel {
 private JPanel container;
    private Enterprise_class enterprise;
    private static Logger log = Logger.getLogger(Manage_UserAccountJPanel.class);
    private static final String CLASS_NAME = Manage_UserAccountJPanel.class.getName();
    /**
     * Creates new form Manage_UserAccountJPanel
     */
    public Manage_UserAccountJPanel(JPanel container, Enterprise_class enterprise_class) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        populateData();
        populateOrganizationComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LBL_ORG = new javax.swing.JLabel();
        jComboBox_ORG = new javax.swing.JComboBox<>();
        LBL_EMP = new javax.swing.JLabel();
        jComboBox_EMP = new javax.swing.JComboBox<>();
        LBL_ROLE = new javax.swing.JLabel();
        jComboBox_ROLE = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        LBL_PASSWORD = new javax.swing.JLabel();
        TXT_USER_NAME = new javax.swing.JTextField();
        TXT_PASSWORD = new javax.swing.JTextField();
        BTN_BACK_MANG_USER_aCC = new javax.swing.JButton();
        BTN_CREATE_USER_aCC = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MANAGE USER ACCOUNT");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USER NAME", "ROLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        LBL_ORG.setText("ORGANIZATION");

        jComboBox_ORG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ORG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ORGActionPerformed(evt);
            }
        });

        LBL_EMP.setText("EMPLOYEEE");

        jComboBox_EMP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_EMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EMPActionPerformed(evt);
            }
        });

        LBL_ROLE.setText("ROLE");

        jComboBox_ROLE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox_ROLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ROLEActionPerformed(evt);
            }
        });

        jLabel2.setText("USER NAME");

        LBL_PASSWORD.setText("PASSWORD");

        TXT_USER_NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_USER_NAMEActionPerformed(evt);
            }
        });

        TXT_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_PASSWORDActionPerformed(evt);
            }
        });

        BTN_BACK_MANG_USER_aCC.setText("BACK");
        BTN_BACK_MANG_USER_aCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACK_MANG_USER_aCCActionPerformed(evt);
            }
        });

        BTN_CREATE_USER_aCC.setText("CREATE USER ACCOUNT");
        BTN_CREATE_USER_aCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CREATE_USER_aCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(LBL_ROLE)
                                .addGap(62, 62, 62)
                                .addComponent(jComboBox_ROLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(LBL_EMP))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(LBL_PASSWORD))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXT_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addComponent(jComboBox_EMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BTN_BACK_MANG_USER_aCC)
                        .addGap(154, 154, 154)
                        .addComponent(BTN_CREATE_USER_aCC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LBL_ORG)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jComboBox_ORG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_ORG)
                    .addComponent(jComboBox_ORG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_EMP)
                    .addComponent(jComboBox_EMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LBL_ROLE)
                    .addComponent(jComboBox_ROLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXT_USER_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_PASSWORD)
                    .addComponent(TXT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_BACK_MANG_USER_aCC)
                    .addComponent(BTN_CREATE_USER_aCC))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_EMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EMPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_EMPActionPerformed

    private void jComboBox_ROLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ROLEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_ROLEActionPerformed

    private void TXT_USER_NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_USER_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_USER_NAMEActionPerformed

    private void TXT_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_PASSWORDActionPerformed

    private void BTN_CREATE_USER_aCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CREATE_USER_aCCActionPerformed
        // TODO add your handling code here:
          String userName = TXT_USER_NAME.getText().trim();
        String password = TXT_PASSWORD.getText();
        org_class organization = (org_class) jComboBox_ORG.getSelectedItem();
        Employee employee = (Employee) jComboBox_EMP.getSelectedItem();
        Role_class role = (Role_class) jComboBox_ROLE.getSelectedItem();
        ArrayList<String>usernamecheck = new ArrayList<>();
        for(User_account_class e: organization.getUserAccountDirectory().getUserAccountList())
        {
            usernamecheck.add(e.getUser_Name());
            
        }
        if(usernamecheck.contains(userName))
        {
            JOptionPane.showMessageDialog(null,"UserName already exists");
            return;
        }
        if(userName.isEmpty()||password.isEmpty())
        {
         JOptionPane.showMessageDialog(null,"Please enter a Valid input");
            return;   
        }
        log.debug("Enterprise admin creating user with name \t" +userName+ "Role" +role+ "In Organization" +organization+ "\t" +CLASS_NAME);
        organization.getUserAccountDirectory().createUserAccount(userName, password, employee, role);
        
        populateData();
        TXT_USER_NAME.setText("");
        TXT_PASSWORD.setText("");
    }//GEN-LAST:event_BTN_CREATE_USER_aCCActionPerformed

    private void BTN_BACK_MANG_USER_aCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACK_MANG_USER_aCCActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_BTN_BACK_MANG_USER_aCCActionPerformed

    private void jComboBox_ORGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ORGActionPerformed
        // TODO add your handling code here:
         org_class organization = (org_class) jComboBox_ORG.getSelectedItem();
        if (organization != null){
            populateEmployeeComboBox(organization);
            populateRoleComboBox(organization);
    }//GEN-LAST:event_jComboBox_ORGActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACK_MANG_USER_aCC;
    private javax.swing.JButton BTN_CREATE_USER_aCC;
    private javax.swing.JLabel LBL_EMP;
    private javax.swing.JLabel LBL_ORG;
    private javax.swing.JLabel LBL_PASSWORD;
    private javax.swing.JLabel LBL_ROLE;
    private javax.swing.JTextField TXT_PASSWORD;
    private javax.swing.JTextField TXT_USER_NAME;
    private javax.swing.JComboBox<String> jComboBox_EMP;
    private javax.swing.JComboBox<String> jComboBox_ORG;
    private javax.swing.JComboBox<String> jComboBox_ROLE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.setRowCount(0);

        for (org_class organization : enterprise.getOrg_Diectory().getOrgList()) {
            for (User_account_class ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) jTable1.getModel()).addRow(row);
            }
        }
    }

    private void populateOrganizationComboBox() {
    jComboBox_ORG.removeAllItems();

        for (org_class organization : enterprise.getOrg_Diectory().getOrgList()) {
            jComboBox_ORG.addItem(organization);
        }
    }
        
private void populateRoleComboBox(org_class organization){
        jComboBox_ROLE.removeAllItems();
        for (Role_class role_class : organization.getSupportedRole()){
            jComboBox_ROLE.addItem(role_class);
        }
    }

public void populateEmployeeComboBox(org_class organization){
        jComboBox_EMP.removeAllItems();
        
        for (Employee employee : organization.getEmployeeDirectory().getEmpList()){
            jComboBox_EMP.addItem(employee);
        }
    }
}
