/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_Drug_Supplier;


    
    private JPanel userProcessContainer;
    private Patient_class patient;
    private drug_org_class drugOrganization;
    private User_account_class userAccount;
    private Network_class network;
    private EcoCommunity business;
    private static Logger log = Logger.getLogger(PopulateNewDrug.class);
    private static final String CLASS_NAME = PopulateNewDrug.class.getName();
    
    /**
     * Creates new form PopulateNewDrug
     */
    public PopulateNewDrug(JPanel userProcessContainer, Patient_class patient, 
            drug_org_class drugOrganization, User_account_class userAccount, Network_class network,
            EcoCommunity business) {
    
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        this.drugOrganization = drugOrganization;
        this.userAccount = userAccount;
        this.network = network;
        this.business = business;
        txtPatientName.setText(patient.getPatient_Name());
        populateTable();
        

    /**
     * Creates new form PopulateNewDrug
     */
    public PopulateNewDrug() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNewDrug = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();


        lblNewDrug.setText("New Drug");

        lblPatientName.setText("Patient Name");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Gene Name", "Compound Mixture"
            }
        ));
        jScrollPane1.setViewportView(jTable1);



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(lblNewDrug))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(lblPatientName)
                        .addGap(100, 100, 100)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))

                        .addComponent(txtlAddNewDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(btnBack)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblNewDrug)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)

                .addGap(37, 37, 37)
                .addComponent(btnBack)
                .addContainerGap(147, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private javax.swing.JLabel lblNewDrug;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtlAddNewDrug;
    // End of variables declaration//GEN-END:variables
}
