/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI_Chemical_Role;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import Business.WorkQueue.ChemicalWorkRequest;
import Business.WorkQueue.DrugWorkRequest;
/**
 *
 * @author dpsmv
 */
public class ChemicalRequestProcessPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChemicalRequestProcessPanel
     */
    
    JPanel userProcessContainer;
    ChemicalWorkRequest request;
    private static Logger log = Logger.getLogger(ChemicalRequestProcessPanel.class);
    private static final String CLASS_NAME = ChemicalRequestProcessPanel.class.getName();
   public ChemicalRequestProcessPanel(JPanel userprocessContainer, ChemicalWorkRequest request) {
        initComponents();
        this.userProcessContainer = userprocessContainer;
        this.request = request;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrugSupplierRquestisbeingProcessed = new javax.swing.JLabel();
        lblChoosedateofDelivery = new javax.swing.JLabel();
        txtDateOfDelivery = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnUpdateStatus = new javax.swing.JButton();

        lblDrugSupplierRquestisbeingProcessed.setText("Drug supplier request is being processed");

        lblChoosedateofDelivery.setText("Choose date of Delivery");

        txtDateOfDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateOfDeliveryActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateStatus.setText("Update Status");
        btnUpdateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblChoosedateofDelivery)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(lblDrugSupplierRquestisbeingProcessed))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(txtDateOfDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnUpdateStatus)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblDrugSupplierRquestisbeingProcessed)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChoosedateofDelivery)
                    .addComponent(txtDateOfDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnBack)
                .addGap(39, 39, 39)
                .addComponent(btnUpdateStatus)
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDateOfDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateOfDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateOfDeliveryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        
         userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Chemical_Workspace_JPanel dwjp = (Chemical_Workspace_JPanel) component;
        dwjp.generate_Table();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStatusActionPerformed
        // TODO add your handling code here:
        
        request.setStatus("Completed");
        /*try{
        int year = Date_of_Delivery.getCalendar().get(Calendar.YEAR);
        int month = Date_of_Delivery.getCalendar().get(Calendar.MONTH);
        int day = Date_of_Delivery.getCalendar().get(Calendar.DAY_OF_MONTH);
        String result = year + "-" + month + "-" + day;
        ((Chemical_class_workrequest) request).setChemiacl_delivery_Time(result);
        txtDateOfDelivery.setText(result);
        JOptionPane.showMessageDialog(null, "Request updated successfully!");
        log.debug("request updated successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null , "please enter the valid date");
            return;
        }*/
        
    }//GEN-LAST:event_btnUpdateStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateStatus;
    private javax.swing.JLabel lblChoosedateofDelivery;
    private javax.swing.JLabel lblDrugSupplierRquestisbeingProcessed;
    private javax.swing.JTextField txtDateOfDelivery;
    // End of variables declaration//GEN-END:variables
}
