/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DOCTORROLE;

/**
 *
 * @author dsnik
 */
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

public class Clinical_Trial_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Clinical_Trial_JPanel
     */
    private JPanel userProcessContainer;
    private LabTestWorkRequest request;
    private static Logger log = Logger.getLogger(Clinical_Trial_JPanel.class);
    private static final String CLASS_NAME = Clinical_Trial_JPanel.class.getName();
    public Clinical_Trial_JPanel(JPanel userProcessContainer, LabTestWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        TXT_PTN_NAME.setText(request.getPatientName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LBL_PTN_NAME = new javax.swing.JLabel();
        TXT_PTN_NAME = new javax.swing.JTextField();
        BTN_BACK_CLINCAL = new javax.swing.JButton();
        BTN_SUBMIT_CLINICAL = new javax.swing.JButton();
        LBL_STATUS = new javax.swing.JLabel();
        jComboBox_STATUS = new javax.swing.JComboBox<>();
        lblClinicaltrialimg = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 255, 153), new java.awt.Color(204, 255, 204), new java.awt.Color(204, 255, 51), new java.awt.Color(204, 255, 102)));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLINICAL TRIAL DASHBOARD");

        LBL_PTN_NAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBL_PTN_NAME.setText("PATIENT NAME");

        BTN_BACK_CLINCAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_BACK_CLINCAL.setText("BACK");
        BTN_BACK_CLINCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACK_CLINCALActionPerformed(evt);
            }
        });

        BTN_SUBMIT_CLINICAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_SUBMIT_CLINICAL.setText("SUBMIT CLINICAL TRIAL");
        BTN_SUBMIT_CLINICAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SUBMIT_CLINICALActionPerformed(evt);
            }
        });

        LBL_STATUS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBL_STATUS.setText("CLINICAL TRIAL STATUS");

        jComboBox_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblClinicaltrialimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/DOCTORROLE/clinicaltrail.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LBL_PTN_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58)
                                    .addComponent(TXT_PTN_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LBL_STATUS)
                                    .addGap(48, 48, 48)
                                    .addComponent(jComboBox_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblClinicaltrialimg, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(BTN_BACK_CLINCAL)
                        .addGap(125, 125, 125)
                        .addComponent(BTN_SUBMIT_CLINICAL)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClinicaltrialimg, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_PTN_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LBL_PTN_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_STATUS)
                    .addComponent(jComboBox_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_BACK_CLINCAL)
                    .addComponent(BTN_SUBMIT_CLINICAL))
                .addGap(160, 160, 160))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_SUBMIT_CLINICALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SUBMIT_CLINICALActionPerformed
        // TODO add your handling code here:  String clinicalStatus = sexcomboBox.getSelectedItem().toString();
          String clinicalStatus = jComboBox_STATUS.getSelectedItem().toString();
      
        if((clinicalStatus == "") || (!clinicalStatus.equalsIgnoreCase("--Please select--"))){
            
             request.getPatient().setClinicalStatus(clinicalStatus);
            log.debug("updated patient status to"+" "+request.getPatient().getClinicalStatus());
            JOptionPane.showMessageDialog(null, "Status has been updated successfully");
    }
        
        else{
            JOptionPane.showMessageDialog(null, "Please select clincal Status");
            log.error("clinical status has not been selected");
        }
        
    }//GEN-LAST:event_BTN_SUBMIT_CLINICALActionPerformed

    private void BTN_BACK_CLINCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACK_CLINCALActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Request_from_Doctor_JPanel Doctor_request = (Request_from_Doctor_JPanel) component;
        Doctor_request.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BTN_BACK_CLINCALActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACK_CLINCAL;
    private javax.swing.JButton BTN_SUBMIT_CLINICAL;
    private javax.swing.JLabel LBL_PTN_NAME;
    private javax.swing.JLabel LBL_STATUS;
    private javax.swing.JTextField TXT_PTN_NAME;
    private javax.swing.JComboBox<String> jComboBox_STATUS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClinicaltrialimg;
    // End of variables declaration//GEN-END:variables
}
