/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DOCTORROLE;

/**
 *
 * @author dsnik
 */
import WorkQueue.lab_class_workrequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;

public class Clinical_Trial_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form Clinical_Trial_JPanel
     */
    private JPanel userProcessContainer;
    private lab_class_workrequest request;
    private static Logger log = Logger.getLogger(Clinical_Trial_JPanel.class);
    private static final String CLASS_NAME = Clinical_Trial_JPanel.class.getName();
    public Clinical_Trial_JPanel(JPanel userProcessContainer, lab_class_workrequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        TXT_PTN_NAME.setText(request.getPatient_Name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LBL_PTN_NAME = new javax.swing.JLabel();
        TXT_PTN_NAME = new javax.swing.JTextField();
        BTN_BACK_CLINCAL = new javax.swing.JButton();
        BTN_SUBMIT_CLINICAL = new javax.swing.JButton();
        LBL_STATUS = new javax.swing.JLabel();
        jComboBox_STATUS = new javax.swing.JComboBox<>();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLINICAL TRIAL DASHBOARD");

        LBL_PTN_NAME.setText("PATIENT NAME");

        BTN_BACK_CLINCAL.setText("BACK");
        BTN_BACK_CLINCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACK_CLINCALActionPerformed(evt);
            }
        });

        BTN_SUBMIT_CLINICAL.setText("SUBMIT CLINICAL TRIAL");
        BTN_SUBMIT_CLINICAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SUBMIT_CLINICALActionPerformed(evt);
            }
        });

        LBL_STATUS.setText("CLINICAL TRIAL STATUS");

        jComboBox_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(BTN_BACK_CLINCAL)
                        .addGap(156, 156, 156)
                        .addComponent(BTN_SUBMIT_CLINICAL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LBL_STATUS)
                            .addComponent(LBL_PTN_NAME))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_PTN_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(BTN_BACK_CLINCAL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_PTN_NAME)
                            .addComponent(TXT_PTN_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LBL_STATUS)
                            .addComponent(jComboBox_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(BTN_SUBMIT_CLINICAL)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_SUBMIT_CLINICALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SUBMIT_CLINICALActionPerformed
        // TODO add your handling code here:  String clinicalStatus = sexcomboBox.getSelectedItem().toString();
          String clinicalStatus = jComboBox_STATUS.getSelectedItem().toString();
      
        if((clinicalStatus == "") || (!clinicalStatus.equalsIgnoreCase("--Please select--"))){
            
            request.getPatient().setClinical_Status(clinicalStatus);
            log.debug("updated patient status to"+" "+request.getPatient().getClinical_Status());
            JOptionPane.showMessageDialog(null, "Status has been updated successfully");
    }
        
        else{
            JOptionPane.showMessageDialog(null, "Please select clincal Status");
            log.error("clinical status has not been selected");
        }
        
    }//GEN-LAST:event_BTN_SUBMIT_CLINICALActionPerformed

    private void BTN_BACK_CLINCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACK_CLINCALActionPerformed
        // TODO add your handling code here:
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Request_from_Doctor_JPanel Doctor_request = (Request_from_Doctor_JPanel) component;
        Doctor_request.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BTN_BACK_CLINCALActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACK_CLINCAL;
    private javax.swing.JButton BTN_SUBMIT_CLINICAL;
    private javax.swing.JLabel LBL_PTN_NAME;
    private javax.swing.JLabel LBL_STATUS;
    private javax.swing.JTextField TXT_PTN_NAME;
    private javax.swing.JComboBox<String> jComboBox_STATUS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
