/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DOCTORROLE;

/**
 *
 * @author dsnik
 */import Doctor.Physician_class;
import Doctor.Prescription_List;
import Business.EcoCommunity;
import Enterprise.Enterprise_class;
import Network.Network_class;
import Organization.Doctor_org_class;
import User_account.User_account_class;
import WorkQueue.Doctor_class_workrequest;
import WorkQueue.Workrequest_class;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

public class DOCTOR_WORK_AREA_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form DOCTOR_WORK_AREA_JPanel
     */private JPanel userProcessContainer;
    private Doctor_org_class doctor_org_class;
    private Enterprise_class enterprise_class;
    private User_account_class user_account_class;
    private Physician_class physician_class;
    private Prescription_List prescription_List;
    private Doctor_class_workrequest doctor_class_workrequest;
    private Network_class network_class;
    private EcoCommunity ecoCommunity;
    private static Logger log = Logger.getLogger(DOCTOR_WORK_AREA_JPanel.class);
    private static final String CLASS_NAME = DOCTOR_WORK_AREA_JPanel.class.getName();
    
    public DOCTOR_WORK_AREA_JPanel(JPanel userProcessContainer, User_account_class user_account_class, Doctor_org_class doctor_org_class, Enterprise_class enterprise_class, EcoCommunity ecoCommunity, Network_class network_class) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.user_account_class = user_account_class;
        this.doctor_org_class = doctor_org_class;
        this.enterprise_class = enterprise_class;
        this.network_class = network_class;
        this.ecoCommunity = ecoCommunity;
        network();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTN_WRITE_PRESCRIPTION = new javax.swing.JButton();
        BTN_LAB_TEST = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCTOR WORK AREA");

        BTN_WRITE_PRESCRIPTION.setText("WRITE PRESCRIPTION");
        BTN_WRITE_PRESCRIPTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_WRITE_PRESCRIPTIONActionPerformed(evt);
            }
        });

        BTN_LAB_TEST.setText("ORDER LAB TEST");
        BTN_LAB_TEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LAB_TESTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_WRITE_PRESCRIPTION, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(BTN_LAB_TEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_WRITE_PRESCRIPTION, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BTN_LAB_TEST, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_LAB_TESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LAB_TESTActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor's lab request");
        userProcessContainer.add("TestJPanel", new UI.DOCTORROLE.REQUEST_LAB_TEST_JPanel(userProcessContainer, user_account_class, doctor_org_class, enterprise_class, ecoCommunity, network_class));

        layout.next(userProcessContainer);
    }//GEN-LAST:event_BTN_LAB_TESTActionPerformed

    private void BTN_WRITE_PRESCRIPTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_WRITE_PRESCRIPTIONActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
          log.debug("inside doctor role");
          userProcessContainer.add("PrescriptionJPanel", new UI.DOCTORROLE.WRITE_PRESCRIPTION_JPanel(userProcessContainer,list,userAccount,enterprise,organization,system,network));
       //  userProcessContainer.add("PrescriptionJPanel", new userinterface.DoctorRole.PrescriptionJPanel(userProcessContainer, userAccount, enterprise));
         layout.next(userProcessContainer);
    }//GEN-LAST:event_BTN_WRITE_PRESCRIPTIONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_LAB_TEST;
    private javax.swing.JButton BTN_WRITE_PRESCRIPTION;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void network() {
    network_class.getName();
    }
}
