/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DOCTORROLE;

/**
 *
 * @author dsnik
 */
import Business.Doctor.Physician;
import Business.Doctor.PrescriptionList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;

public class DOCTOR_WORK_AREA_JPanel extends javax.swing.JPanel {

    /**
     * Creates new form DOCTOR_WORK_AREA_JPanel
     */ private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Physician physician;
    private PrescriptionList list;
    private DoctorWorkRequest docreq;
    private Network network;
    private EcoSystem system;
    private static Logger log = Logger.getLogger(DOCTOR_WORK_AREA_JPanel.class);
    private static final String CLASS_NAME = DOCTOR_WORK_AREA_JPanel.class.getName();

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DOCTOR_WORK_AREA_JPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization organization, Enterprise enterprise, EcoSystem system, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTN_WRITE_PRESCRIPTION = new javax.swing.JButton();
        BTN_LAB_TEST = new javax.swing.JButton();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DOCTOR WORK AREA");

        BTN_WRITE_PRESCRIPTION.setText("WRITE PRESCRIPTION");
        BTN_WRITE_PRESCRIPTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_WRITE_PRESCRIPTIONActionPerformed(evt);
            }
        });

        BTN_LAB_TEST.setText("ORDER LAB TEST");
        BTN_LAB_TEST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LAB_TESTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_WRITE_PRESCRIPTION, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(BTN_LAB_TEST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_WRITE_PRESCRIPTION, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(BTN_LAB_TEST, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_LAB_TESTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LAB_TESTActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        log.debug("inside doctor's lab request");
          userProcessContainer.add("PrescriptionJPanel", new UI.DOCTORROLE.WRITE_PRESCRIPTION_JPanel(userProcessContainer,list,userAccount,enterprise,organization,system,network));
      
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BTN_LAB_TESTActionPerformed

    private void BTN_WRITE_PRESCRIPTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_WRITE_PRESCRIPTIONActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
          log.debug("inside doctor role");
       userProcessContainer.add("TestJPanel", new UI.DOCTORROLE.Request_from_Doctor_JPanel(userProcessContainer, userAccount, organization, enterprise, system, network));
 //  userProcessContainer.add("PrescriptionJPanel", new userinterface.DoctorRole.PrescriptionJPanel(userProcessContainer, userAccount, enterprise));
         layout.next(userProcessContainer);
    }//GEN-LAST:event_BTN_WRITE_PRESCRIPTIONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_LAB_TEST;
    private javax.swing.JButton BTN_WRITE_PRESCRIPTION;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void network() {
    network.getName();
    }
}
