/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DOCTORROLE;

/**
 *
 * @author dsnik
 */
import Genetics.Genetic_class;

import WorkQueue.lab_class_workrequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
public class REQUEST_LAB_TEST_JPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private lab_class_workrequest request;
    private static Logger log = Logger.getLogger(REQUEST_LAB_TEST_JPanel.class);
    private static final String CLASS_NAME = REQUEST_LAB_TEST_JPanel.class.getName();
    /**
     * Creates new form REQUEST_LAB_TEST_JPanel
     */
    public REQUEST_LAB_TEST_JPanel(JPanel userProcessContainer, lab_class_workrequest request) {
        initComponents();
           this.userProcessContainer = userProcessContainer;
        this.request = request;
        TXT_PATIENT_NAME.setText(request.getPatient_Name());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LBL_LAB_TEST_RESULTS = new javax.swing.JLabel();
        LBL_PATIENT_NAME = new javax.swing.JLabel();
        TXT_PATIENT_NAME = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_LAB_REULTS = new javax.swing.JTable();
        BTN_BACK = new javax.swing.JButton();

        LBL_LAB_TEST_RESULTS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBL_LAB_TEST_RESULTS.setText("LAB TEST RESULTS");

        LBL_PATIENT_NAME.setText("PATIENT NAME");

        jTable_LAB_REULTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "GENE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_LAB_REULTS);

        BTN_BACK.setText("BACK");
        BTN_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(LBL_LAB_TEST_RESULTS, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(LBL_PATIENT_NAME)
                        .addGap(107, 107, 107)
                        .addComponent(TXT_PATIENT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(BTN_BACK)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(LBL_LAB_TEST_RESULTS, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBL_PATIENT_NAME)
                    .addComponent(TXT_PATIENT_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(BTN_BACK)
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACKActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Request_from_Doctor_JPanel LAB_REQUEST = (Request_from_Doctor_JPanel) component;
        LAB_REQUEST.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BTN_BACKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACK;
    private javax.swing.JLabel LBL_LAB_TEST_RESULTS;
    private javax.swing.JLabel LBL_PATIENT_NAME;
    private javax.swing.JTextField TXT_PATIENT_NAME;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_LAB_REULTS;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
 DefaultTableModel model = (DefaultTableModel) jTable_LAB_REULTS.getModel();

        model.setRowCount(0);
        System.out.println(((lab_class_workrequest) request).getPatient().getGene_History().getGenetics_History());
        System.out.println(((lab_class_workrequest) request).getPatient().getGene_History().getGenetics_History().size());

        for (Genetic_class g : ((lab_class_workrequest) request).getPatient().getGene_History().getGenetics_History()) {

            Object[] row = new Object[2];
            row[0] = g.getGene_id();
            row[1] = g.getGene_Name();
            System.out.println(((lab_class_workrequest) request).getPatient());

            model.addRow(row);
            log.debug("displaying results");
        }
    }

}
